//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.08.25 at 08:55:07 AM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opengis.net/citygml/vegetation/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.ign.cogit.geoxygene.sig3d.model.citygml.vegetation;

