//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.08.25 at 08:55:07 AM CEST
//

package fr.ign.cogit.geoxygene.sig3d.model.citygml.core;

import java.util.List;

import org.citygml4j.model.citygml.core.GeneralizationRelation;

public class CG_GeneralizationRelation {

  protected List<? extends CG_CityObject> cityObject;
  protected String remoteSchema;

  protected String type;

  protected String href;

  protected String role;

  protected String arcrole;

  protected String title;

  protected String show;

  protected String actuate;

  public List<? extends CG_CityObject> get_CityObject() {
    return this.cityObject;
  }

  public CG_GeneralizationRelation(GeneralizationRelation gr) {
    super();
    System.out.println("GeneralizationRelationType constructeur vide");
  }

  public void set_CityObject(List<? extends CG_CityObject> value) {
    this.cityObject = value;
  }

  public boolean isSet_CityObject() {
    return (this.cityObject != null);
  }

  /**
   * Gets the value of the remoteSchema property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRemoteSchema() {
    return this.remoteSchema;
  }

  /**
   * Sets the value of the remoteSchema property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRemoteSchema(String value) {
    this.remoteSchema = value;
  }

  public boolean isSetRemoteSchema() {
    return (this.remoteSchema != null);
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getType() {
    if (this.type == null) {
      return "simple";
    } else {
      return this.type;
    }
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setType(String value) {
    this.type = value;
  }

  public boolean isSetType() {
    return (this.type != null);
  }

  /**
   * Gets the value of the href property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getHref() {
    return this.href;
  }

  /**
   * Sets the value of the href property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setHref(String value) {
    this.href = value;
  }

  public boolean isSetHref() {
    return (this.href != null);
  }

  /**
   * Gets the value of the role property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRole() {
    return this.role;
  }

  /**
   * Sets the value of the role property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRole(String value) {
    this.role = value;
  }

  public boolean isSetRole() {
    return (this.role != null);
  }

  /**
   * Gets the value of the arcrole property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getArcrole() {
    return this.arcrole;
  }

  /**
   * Sets the value of the arcrole property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setArcrole(String value) {
    this.arcrole = value;
  }

  public boolean isSetArcrole() {
    return (this.arcrole != null);
  }

  /**
   * Gets the value of the title property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTitle() {
    return this.title;
  }

  /**
   * Sets the value of the title property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTitle(String value) {
    this.title = value;
  }

  public boolean isSetTitle() {
    return (this.title != null);
  }

  /**
   * Gets the value of the show property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getShow() {
    return this.show;
  }

  /**
   * Sets the value of the show property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setShow(String value) {
    this.show = value;
  }

  public boolean isSetShow() {
    return (this.show != null);
  }

  /**
   * Gets the value of the actuate property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getActuate() {
    return this.actuate;
  }

  /**
   * Sets the value of the actuate property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setActuate(String value) {
    this.actuate = value;
  }

  public boolean isSetActuate() {
    return (this.actuate != null);
  }

}
