/* Generated By:JavaCC: Do not edit this line. WktGeOxygeneConstants.java */
package fr.ign.cogit.geoxygene.util.conversion;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WktGeOxygeneConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 1;
  /** RegularExpression Id. */
  int FLOAT = 2;
  /** RegularExpression Id. */
  int INTEGER = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int POINT = 5;
  /** RegularExpression Id. */
  int EOL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  @SuppressWarnings("nls")
String[] tokenImage = {
    "<EOF>",
    "<CONSTANT>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<POINT>",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\"EMPTY\"",
    "\",\"",
    "\"POINT\"",
    "\"Z\"",
    "\"M\"",
    "\"MULTIPOINT\"",
    "\"LINESTRING\"",
    "\"MULTILINESTRING\"",
    "\"POLYGON\"",
    "\"MULTIPOLYGON\"",
    "\"GEOMETRYCOLLECTION\"",
  };

}
