//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.25 at 02:52:10 PM CEST 
//


package fr.ign.cogit.geoxygene.matching;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.ign.cogit.geoxygene.matching package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.ign.cogit.geoxygene.matching
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Matchings.Matching.Pattern }
     * 
     */
    public Matchings.Matching.Pattern createMatchingsMatchingPattern() {
        return new Matchings.Matching.Pattern();
    }

    /**
     * Create an instance of {@link Matchings }
     * 
     */
    public Matchings createMatchings() {
        return new Matchings();
    }

    /**
     * Create an instance of {@link Matchings.Matching }
     * 
     */
    public Matchings.Matching createMatchingsMatching() {
        return new Matchings.Matching();
    }

}
