SELECT DropGeometryColumn('batiment','geom');
SELECT DropGeometryColumn('carrefour','geom');
SELECT DropGeometryColumn('cimetiere','geom');
SELECT DropGeometryColumn('zone_elementaire_urbaine','geom');
SELECT DropGeometryColumn('zone_elementaire_peri_urbaine','geom');
SELECT DropGeometryColumn('infrastructure_communication','geom');
SELECT DropGeometryColumn('parking','geom');
SELECT DropGeometryColumn('surface_eau','geom');
SELECT DropGeometryColumn('terrain_sport','geom');
SELECT DropGeometryColumn('troncon_chemin','geom');
SELECT DropGeometryColumn('troncon_cours_eau','geom');
SELECT DropGeometryColumn('troncon_route','geom');
SELECT DropGeometryColumn('troncon_voie_ferree','geom');
SELECT DropGeometryColumn('vegetation','geom');
SELECT DropGeometryColumn('unite_urbaine','geom');
SELECT DropGeometryColumn('unite_peri_urbaine','geom');
SELECT DropGeometryColumn('espace_vide','geom');
SELECT DropGeometryColumn('groupe_batiments','geom');
SELECT DropGeometryColumn('alignement','geom');

DROP TABLE agentgeo;
DROP TABLE batiment;
DROP TABLE carrefour;
DROP TABLE cimetiere;
DROP TABLE zone_elementaire_urbaine;
DROP TABLE zone_elementaire_peri_urbaine;
DROP TABLE infrastructure_communication;
DROP TABLE parking;
DROP TABLE relation_zone_elem_zone_elem;
DROP TABLE relation_zone_elem_troncon;
DROP TABLE surface_eau;
DROP TABLE terrain_sport;
DROP TABLE troncon_chemin;
DROP TABLE troncon_cours_eau;
DROP TABLE troncon_route;
DROP TABLE troncon_voie_ferree;
DROP TABLE vegetation;
DROP TABLE unite_urbaine;
DROP TABLE unite_peri_urbaine;
DROP TABLE espace_vide;
DROP TABLE relation_agent_agent;
DROP TABLE groupe_batiments;
DROP TABLE alignement;
DROP TABLE relation_alignement_batiment;
