package fr.ign.cogit.geoxygene.osm.anonymization.db.access.queries;


/**
 * Enumération indiquant les types de requêtes 
 * utilisées dans 
 * {@link fr.ign.cogit.geoxygene.osm.anonymization.db.SQLDBPreAnonymization}
 * et attendus dans en tant que clé dans 
 * {@link fr.ign.cogit.geoxygene.osm.anonymization.db.access.queries.PreAnonymizationQueries}.
 * 
 * @author Matthieu Dufait
 */
public enum PreAnonymizationQueriesType {
  CREATE_CHANGESET_TABLE,
  CREATE_USER_TABLE,
  
  DROP_COLUMNS_NODE,
  DROP_COLUMNS_WAY,
  DROP_COLUMNS_RELATION,
  DROP_COLUMNS_MEMBER,
  
  // Deprecie pour pouvoir
  // corriger la base
  // après la pré-anonymisation.
  /*DROP_ID_NODE,
  DROP_ID_WAY,
  DROP_ID_RELATION,
  DROP_ID_MEMBER,*/
  
  ADD_COLUMNS_CHANGESET,
  UPDATE_DATA_CHANGESET,
  SELECT_CHANGESET_ID,
  
  SELECT_ID_NODE,
  SELECT_ID_WAY,
  SELECT_ID_RELATION,
  
  ADD_VISIBLE_NODE,
  ADD_VISIBLE_WAY,
  ADD_VISIBLE_RELATION,
  
  UPDATE_VISIBLE_NODE,
  UPDATE_VISIBLE_WAY,
  UPDATE_VISIBLE_RELATION, 
  
  DROP_DATE_NODE,
  DROP_DATE_WAY,
  DROP_DATE_RELATION, 
  
  UPDATE_DATE_CHANGESET, 
  SELECT_DATE_CHANGESET,
  
  ADD_VERSION_MEMBER,
  UPDATE_VERSION_MEMBER,
  
  // ID SHUFFLING
  
  // ID CONTRIBUTOR
  CREATE_ANON_CONTRIBUTOR, 
  UPDATE_CHANGESET_UID, 
  DROP_UID_CONTRIBUTOR, 
  REPLACE_UID_CONTRIBUTOR, 
  DROP_TABLE_CONTRIBUTOR, 
  REPLACE_TABLE_CONTRIBUTOR, 
  
  // ID CHANGESET
  CREATE_ANON_CHANGESET, 
  UPDATE_CHANGESET_IN_NODE, 
  UPDATE_CHANGESET_IN_WAY, 
  UPDATE_CHANGESET_IN_RELATION, 
  DROP_CHANGESET_ID, 
  REPLACE_CHANGESET_ID, 
  DROP_TABLE_CHANGESET, 
  REPLACE_TABLE_CHANGESET, 
  
  // ID ELEMENTS
  CREATE_ANON_NODE, 
  CREATE_ANON_WAY, 
  CREATE_ANON_RELATION, 
    // WAY_NODES
  CREATE_WAY_NODES, 
  UPDATE_WAY_NODES_IDS, 
  DROP_COMPOSEDOF_WAY, 
    // MEMBERS
  UPDATE_RELATIONMEMBER_REL_REF, 
  UPDATE_RELATIONMEMBER_MB_RELATION, 
  UPDATE_RELATIONMEMBER_MB_WAY, 
  UPDATE_RELATIONMEMBER_MB_NODE, 
  UPDATE_ID_NODE, 
  UPDATE_ID_WAY, 
  UPDATE_ID_RELATION, 
  DROP_ANON_NODE, 
  DROP_ANON_WAY, 
  DROP_ANON_RELATION, 
  
  // BAD IDS
  DROP_BAD_ID_NODE, 
  DROP_BAD_ID_WAY, 
  DROP_BAD_ID_RELATION, 
  DROP_BAD_ID_RELATIONMEMBER, 
  
  // PRIMARY KEYS
  ADD_PRIMARY_CONTRIBUTOR, 
  ADD_PRIMARY_WAY_NODES, 
  ADD_PRIMARY_CHANGESET, 
  ADD_PRIMARY_NODE, 
  ADD_PRIMARY_WAY, 
  ADD_PRIMARY_RELATION, 
  ADD_PRIMARY_RELATIONMEMBER,
  
}
