//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.08.25 at 08:55:07 AM CEST
//

package fr.ign.cogit.geoxygene.sig3d.model.citygml.relief;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import fr.ign.cogit.geoxygene.schema.schemaConceptuelISOJeu.AssociationType;

/**
 * Denotes the relation of a RasterReliefType to its components. The
 * gridPropertyType element must either carry a reference to a
 * gml:RectifiedGridCoverage object or contain a gml:RectifiedGridCoverage
 * object inline, but neither both nor none.
 * 
 * <p>
 * Java class for gridPropertyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="gridPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.opengis.net/gml}AssociationType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{http://www.opengis.net/gml}RectifiedGridCoverage"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gridPropertyType")
public class CG_GridProperty extends AssociationType {

}
