//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.08.25 at 08:55:07 AM CEST
//

package fr.ign.cogit.geoxygene.sig3d.model.citygml.generics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for DateAttributeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DateAttributeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/citygml/generics/1.0}AbstractGenericAttributeType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateAttributeType", propOrder = { "value" })
public class CG_DateAttribute extends CG_AbstractGenericAttribute {

  @XmlElement(required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar value;

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getValue() {
    return this.value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setValue(XMLGregorianCalendar value) {
    this.value = value;
  }

  public boolean isSetValue() {
    return (this.value != null);
  }

}
