/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation */

#ifndef _Included_fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation
#define _Included_fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation
#ifdef __cplusplus
extern "C" {
#endif
#undef fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation_SPAGHETTI
#define fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation_SPAGHETTI 0L
#undef fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation_NETWORK
#define fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation_NETWORK 1L
#undef fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation_MAP
#define fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation_MAP 2L
/*
 * Class:     fr_ign_cogit_appli_risques_triangulation_Triangulation
 * Method:    trianguleC
 * Signature: (Ljava/lang/String;Lfr/ign/cogit/geoxygene/contrib/delaunay/Triangulateio;Lfr/ign/cogit/geoxygene/contrib/delaunay/Triangulateio;Lfrfr/ign/cogit/geoxygene/contrib/delaunay/Triangulateio;)V
 */
JNIEXPORT void JNICALL Java_fr_ign_cogit_geoxygene_contrib_delaunay_Triangulation_trianguleC
  (JNIEnv *, jobject, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
